export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CURRENT_USER_DETAIL_SUCCESS = 'CURRENT_USER_DETAIL_SUCCESS';
export const CURRENT_USER_DETAIL_FAILURE = 'CURRENT_USER_DETAIL_FAILURE';

export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAILURE = 'USERS_LIST_FAILURE';

export const CONNECTION_OPENING = 'CONNECTION_OPENING';
export const CONNECTION_SUBSCRIBING = 'CONNECTION_SUBSCRIBING';
export const CONNECTION_READY = 'CONNECTION_READY';

export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS';
export const CONVERSATION_LIST_FAILURE = 'CONVERSATION_LIST_FAILURE';

